### ISSUE TITLE
Table Bug

### ISSUE THREAD

**Issue by janki-r-patel** [syncfusion/ej2-showcase-aspnetmvc-loan-calculator#2]
Amortisation Schedule table is not been displayed..
If remove <ng-template> then it displays table without span if <ng-template> is there then it does not display data table.

**Comment by SowmiyaPadmanaban** [comment]
Hi Janki, 

We have checked your reported issue with Loan Calculator. When updating the Syncfusion.EJ2.MVC5 package to the latest version (v18.2.0.47). We have facing some issue in Chart component because types are not provided properly in the controller.

Refer the below code snippet.
```
public ActionResult Index() 
        {
            ViewBag.animation = new AccumulationChartAnimation { Enable = true };
            ViewBag.majorGridLines = new ChartMajorGridLines { Width = 0.00001 };
            ViewBag.minorGridLines = new ChartMinorGridLines { Width = 0.00001 };
}
```
After resolving the above issue, Schedule component rendered properly in the application.

Refer the below screenshot.
![image](https://user-images.githubusercontent.com/55983550/88932303-8452bc80-d29b-11ea-9642-a14d5b8a8ddb.png)

Refer the updated sample link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/LoanCalculator3688700941534413834.zip

Please let us know, if you need any further assistance.

Regards, 
Sowmiya.P

**Comment by rajendranr-5483** [comment]
Hi All,

This issue has not had any activity for long time. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.

Regards,
Rajendran R
